language: c

compiler:
  - gcc

install: 
  - sudo apt-get update || true
  - sudo apt-get install build-essential
  - sudo apt-get install libpcap-dev

script:
  - sudo cc -o hepipe hepipe.c -lpcap 
  - ./hepipe -h
